### ISSUE TITLE
Non-compatible with Laravel 11

### ISSUE THREAD

**Issue by Nathan13768609** [HelgeSverre/milvus#1]
Fails to run `composer require helgesverre/milvus` in Laravel 11 project.

## Error Message

> Problem 1
>    - spatie/laravel-data[3.10.0, ..., 3.11.2] require illuminate/contracts ^9.30|^10.0 -> found illuminate/contracts[v9.30.0, ..., v9.52.16, v10.0.0, ..., v10.48.7] but these were not loaded, likely because it conflicts with another require.
>    - helgesverre/milvus[v0.0.1, ..., v0.0.3] require spatie/laravel-data ^3.10 -> satisfiable by spatie/laravel-data[3.10.0, ..., 3.11.2].
>    - Root composer.json requires helgesverre/milvus * -> satisfiable by helgesverre/milvus[v0.0.1, v0.0.2, v0.0.3].

## Solution
My initial thought was to fork off this repo and run a `composer update` command to bring the packages up to date with those used in Laravel 11. However, it was fine for me to just downgrade to laravel 10 in this case, so I just took the easy way out. Just wanted to make this issue known.

**Comment by HelgeSverre** [comment]
Will update the package to laravel 11 over the weekend if i get time.
